name: Release to itch.io

on:
  push:
    tags:
    - 'v*'

env:
  ITCH_USER_NAME: apos
  ITCH_GAME_NAME: projectcore
  PROJECT_PATH: Platforms/DesktopGL
  PROJECT_PATH_WEB: Platforms/BlazorGL.KNI

jobs:
  build:

    runs-on: ubuntu-24.04

    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x
          8.0.x
    - name: Get version from tag
      run: |
        TAGVERSION=$(git describe --tags --abbrev=0)
        echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV
    - name: Setup Wine
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install wget curl p7zip-full wine64
        wget -qO- https://raw.githubusercontent.com/MonoGame/monogame.github.io/1b6099cf90c4aefe311b6d8fdbcdd55fec3770aa/website/content/public/downloads/winesetup/net9_mgfxc_wine_setup.sh | sh
    - name: Build Windows
      run: dotnet publish ${{ env.PROJECT_PATH }} -r win-x64 -c Release --output artifacts/windows --self-contained -p:Version=${{ env.TAGVERSION }}
    - name: Build Osx
      run: dotnet publish ${{ env.PROJECT_PATH }} -r osx-x64 -c Release --output artifacts/osx --self-contained -p:Version=${{ env.TAGVERSION }}
    - name: Build Linux
      run: dotnet publish ${{ env.PROJECT_PATH }} -r linux-x64 -c Release --output artifacts/linux --self-contained -p:Version=${{ env.TAGVERSION }}
    - name: Build Web
      run: |
        dotnet restore ${{ env.PROJECT_PATH_WEB }}
        cp /home/runner/work/ProjectCore/ProjectCore/.github/script/nkast.Xna.Framework.Content.Pipeline.Builder.targets /home/runner/.nuget/packages/nkast.xna.framework.content.pipeline.builder/4.2.9001/build/
        chmod +x /home/runner/.nuget/packages/nkast.xna.framework.content.pipeline.builder/4.2.9001/tools/MGCB.exe
        chmod +x /home/runner/.nuget/packages/nkast.xna.framework.content.pipeline.builder/4.2.9001/Tools/MGCB.exe
        dotnet /home/runner/.nuget/packages/nkast.xna.framework.content.pipeline.builder/4.2.9001/tools/MGCB.dll
        dotnet publish ${{ env.PROJECT_PATH_WEB }} -c Release --output artifacts/web -p:Version=${{ env.TAGVERSION }}
    - name: Publish Windows build to itch.io
      uses: yeslayla/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: windows
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: artifacts/windows
        VERSION: ${{ env.TAGVERSION }}
    - name: Publish OSX build to itch.io
      uses: yeslayla/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: osx
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: artifacts/osx
        VERSION: ${{ env.TAGVERSION }}
    - name: Publish Linux build to itch.io
      uses: yeslayla/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: linux
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: artifacts/linux
        VERSION: ${{ env.TAGVERSION }}
    - name: Publish Web build to itch.io
      uses: yeslayla/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: web
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: artifacts/web
        VERSION: ${{ env.TAGVERSION }}
